apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: qcloudregistrykey
      containers:
      - name: myapp
        image: nginx:1.14.2
        ports:
        - containerPort: 80
