apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: myapp
  env: test

resources:
- deployment.yaml
- service.yaml

namespace: yhj

patchesStrategicMerge:
- deployment.yaml
images:
- name: nginx
  newName: nginx
  newTag: 1.14.2
